In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\padal\OneDrive\Desktop\Data Science\Lungcapdata.csv")
df

     LungCap  Age  Height Smoke  Gender Caesarean   AgeRange
0      6.475    6    62.1    no    male        no   Age 6-15
1     10.125   18    74.7   yes  female        no  Age 16-19
2      9.550   16    69.7    no  female       yes  Age 16-19
3     11.125   14    71.0    no    male        no   Age 6-15
4      4.800    5    56.9    no    male        no    Under 5
..       ...  ...     ...   ...     ...       ...        ...
720    5.725    9    56.0    no  female        no   Age 6-15
721    9.050   18    72.0   yes    male       yes  Age 16-19
722    3.850   11    60.5   yes  female        no   Age 6-15
723    9.825   15    64.9    no  female        no   Age 6-15
724    7.100   10    67.7    no    male        no   Age 6-15

[725 rows x 7 columns]

In [2]:
mean = df["LungCap"].mean()
std = df["LungCap"].std()
print(mean)
print(std)

7.863147586206895
2.662008248678719

In [8]:
from scipy.stats import norm
CI = norm.interval(confidence=0.95, loc=mean, scale=std)
print(f"We are 95% confident that lungcap mean will lie under {CI} ")

We are 95% confident that lungcap mean will lie under (2.645707292248062, 13.080587880165728)